# Generated by Django 4.1.2 on 2022-10-27 12:59

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_address_id_alter_coupon_id_alter_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='country',
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='duration',
            field=models.PositiveBigIntegerField(choices=[('oneweek', (('day', 7),)), ('twoweeks', (('day', 14),)), ('onemonth', (('day', 30),)), ('threemonths', (('day', 91),)), ('sixmonths', (('day', 183),)), ('oneyear', (('day', 365),))], default=7),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='subtype',
            field=models.CharField(choices=[('oneweek', (('pay', 10.7),)), ('twoweeks', (('pay', 18.42),)), ('onemonth', (('pay', 95.3),)), ('threemonths', (('pay', 170),)), ('sixmonths', (('pay', 182),)), ('oneyear', (('pay', 279),))], max_length=10),
        ),
    ]
