# Generated by Django 4.1.2 on 2022-10-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_useraccount_country_alter_useraccount_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='active',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='subtype',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='tranxid',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='filename',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='phone',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='state',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='country',
            field=models.CharField(max_length=200),
        ),
    ]
