# Generated by Django 4.1.2 on 2022-10-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_useraccount_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='date',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='address',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='country',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='filename',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='phone',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='state',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
